export const MVP_COUNTRIES = [
  "USA",
  "CHN",
  "EGY",
  "ETH",
  "RUS",
  "UKR",
  "IND",
  "PAK",
  "ISR",
  "IRN",
  "SAU",
  "TUR",
] as const;

export const MVP_RELATIONSHIP_PAIRS = [
  ["CHN", "USA"],
  ["EGY", "ETH"],
  ["RUS", "UKR"],
  ["IND", "PAK"],
  ["IRN", "ISR"],
  ["IRN", "SAU"],
  ["SAU", "TUR"],
  ["RUS", "TUR"],
] as const;

export const COUNTRY_MODULES = [
  "identity_foundation",
  "history",
  "founding_groups",
  "religion_history",
  "demographics",
  "demographic_change",
  "cultural_assimilation",
  "population_divisions",
  "nationalism_cohesion",
  "national_cohesion_by_demographic",
  "government_current",
  "ruling_class",
  "leader_dossiers",
  "crime_safety",
  "education",
  "economy",
  "trade_exports_imports",
  "production_industry",
  "logistics_shipping_air_travel",
  "household_income_wealth",
  "technology_contributions",
  "math_contributions",
  "philosophy_contributions",
  "military",
  "intelligence_security",
  "media_information",
  "foreign_policy",
  "adversary_narratives",
  "average_citizen_life",
  "game_theory_profile",
  "future_scenarios",
  "allies_and_partners",
  "adversaries_and_rivals",
  "national_event_timeline",
  "top_national_events_20_years",
  "news_memory",
  "threat_perception",
  "wikipedia_baseline",
  "wikipedia_references",
  "scorecard",
] as const;

export const RELATIONSHIP_MODULES = [
  "relationship",
  "trade_relationship",
  "military_relationship",
  "rivalry_narratives",
  "game_theory_relationship",
  "relationship_event_timeline",
  "alliance_status",
  "adversary_status",
  "crisis_history",
  "war_history",
  "diplomatic_history",
] as const;

export const HUMAN_REVIEW_COUNTRY_MODULES = [
  "founding_groups",
  "religion_history",
  "leader_dossiers",
  "adversary_narratives",
  "math_contributions",
  "philosophy_contributions",
  "future_scenarios",
  "game_theory_profile",
  "allies_and_partners",
  "adversaries_and_rivals",
  "national_event_timeline",
  "top_national_events_20_years",
  "news_memory",
  "threat_perception",
  "wikipedia_baseline",
  "wikipedia_references",
] as const;

export const WORLD_BANK_INDICATORS: Record<string, string> = {
  gdp_current_usd: "NY.GDP.MKTP.CD",
  gdp_per_capita_current_usd: "NY.GDP.PCAP.CD",
  gdp_ppp_current_international: "NY.GDP.MKTP.PP.CD",
  population_total: "SP.POP.TOTL",
  urban_population_share: "SP.URB.TOTL.IN.ZS",
  fertility_rate: "SP.DYN.TFRT.IN",
  life_expectancy: "SP.DYN.LE00.IN",
  net_migration: "SM.POP.NETM",
  exports_goods_services_current_usd: "NE.EXP.GNFS.CD",
  imports_goods_services_current_usd: "NE.IMP.GNFS.CD",
  manufacturing_value_added_current_usd: "NV.IND.MANF.CD",
  agriculture_value_added_current_usd: "NV.AGR.TOTL.CD",
  energy_use_kg_oil_equivalent_per_capita: "EG.USE.PCAP.KG.OE",
  electric_power_consumption_kwh_per_capita: "EG.USE.ELEC.KH.PC",
  air_passengers_carried: "IS.AIR.PSGR",
  air_freight_million_ton_km: "IS.AIR.GOOD.MT.K1",
  tourism_arrivals: "ST.INT.ARVL",
  remittances_received_current_usd: "BX.TRF.PWKR.CD.DT",
  fdi_inflows_current_usd: "BX.KLT.DINV.CD.WD",
  poverty_rate_national: "SI.POV.NAHC",
  youth_unemployment_rate: "SL.UEM.1524.ZS",
  gini_index: "SI.POV.GINI",
  literacy_rate_adult: "SE.ADT.LITR.ZS",
  homicide_rate_per_100k: "VC.IHR.PSRC.P5",
  military_expenditure_current_usd: "MS.MIL.XPND.CD",
  patent_applications_residents: "IP.PAT.RESD",
  high_technology_exports_current_usd: "TX.VAL.TECH.CD",
  rd_expenditure_percent_gdp: "GB.XPD.RSDV.GD.ZS",
};

export const MODULE_TOPIC_TAGS: Record<string, string[]> = {
  demographics: ["country-demographics"],
  demographic_change: ["country-demographic-change"],
  cultural_assimilation: ["country-cultural-assimilation"],
  population_divisions: ["country-population-divisions"],
  national_cohesion_by_demographic: ["country-national-cohesion"],
  crime_safety: ["country-crime", "safety"],
  education: ["country-education"],
  economy: ["country-economy"],
  trade_exports_imports: ["country-trade"],
  production_industry: ["country-production"],
  logistics_shipping_air_travel: ["country-logistics"],
  technology_contributions: ["country-technology-contribution"],
  military: ["country-military"],
  foreign_policy: ["country-foreign-policy"],
  average_citizen_life: ["country-average-citizen-life"],
  game_theory_profile: ["country-game-theory"],
  allies_and_partners: ["country-allies"],
  adversaries_and_rivals: ["country-adversaries"],
  national_event_timeline: ["country-event-timeline"],
  top_national_events_20_years: ["country-top-events-20-years"],
  news_memory: ["country-news-memory"],
  threat_perception: ["country-threat-perception"],
  wikipedia_baseline: ["country-wikipedia-baseline"],
  wikipedia_references: ["country-wikipedia-references"],
  relationship: ["relationship-overview"],
  trade_relationship: ["relationship-trade"],
  military_relationship: ["relationship-military"],
  rivalry_narratives: ["relationship-rivalry"],
  game_theory_relationship: ["relationship-red-lines", "relationship-escalation-paths"],
  relationship_event_timeline: ["relationship-top-events-20-years"],
  alliance_status: ["relationship-alliance-status"],
  adversary_status: ["relationship-adversary-status"],
  crisis_history: ["relationship-crisis-history"],
  war_history: ["relationship-war-history"],
  diplomatic_history: ["relationship-diplomatic-history"],
};
